# enables the mouse
set -g mouse on

# Statusbar on top
set -g status-position top

# Set extended keys
set -g extended-keys-format csi-u
set -g extended-keys on

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"
