[greeter]
background=/usr/share/backgrounds/dotfiles/leaves_line_neon_139772_2560x1600.jpg
user-background=false
transition-duration=0
transition-type=none
theme-name=catppuccin-macchiato-blue-standard+default
icon-theme-name=Adwaita
cursor-theme-name=Adwaita
cursor-theme-size=24
font-name=JetBrainsMono Nerd Font 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
active-monitor=#cursor
position=50%,center 50%,center
hide-user-image=true
default-user-image=#avatar-default
panel-position=top
indicators=~host;~spacer;~clock;~spacer;~session;~language;~power
clock-format=%A, %d %B %Y  %H:%M
screensaver-timeout=0
