# Gruvbox Dark desktop profile.
set $theme_env env XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway GTK_THEME=Gruvbox-Dark GTK_USE_PORTAL=1 QT_STYLE_OVERRIDE=kvantum QT_QPA_PLATFORMTHEME=gtk3 QT_QPA_PLATFORM=wayland
output * bg #282828 solid_color
exec_always --no-startup-id sh -c 'data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}; exec swaymsg output "*" bg "$data_home/backgrounds/dotfiles/luca-bravo-zAjdgNXsMeg.jpg" fill'
#                    border   background text     indicator child_border
client.focused          #83a598 #83a598 #282828 #83a598    #83a598
client.focused_inactive #665c54 #282828 #d5c4a1 #665c54    #665c54
client.unfocused        #3c3836 #282828 #928374 #3c3836    #3c3836
client.urgent           #fb4934 #fb4934 #282828 #fabd2f    #fb4934
client.placeholder      #504945 #282828 #ebdbb2 #504945    #504945
client.background       #282828
