# Gruvbox Dark
color=282828
font=JetBrainsMono Nerd Font
font-size=20
indicator-radius=100
indicator-thickness=5
inside-color=282828
inside-clear-color=282828
inside-ver-color=282828
inside-wrong-color=282828
ring-color=d65d0e
ring-clear-color=fabd2f
ring-ver-color=b8bb26
ring-wrong-color=fb4934
line-color=00000000
line-clear-color=00000000
line-ver-color=00000000
line-wrong-color=00000000
separator-color=00000000
key-hl-color=b8bb26
bs-hl-color=fb4934
text-color=ebdbb2
text-clear-color=fabd2f
text-ver-color=b8bb26
text-wrong-color=fb4934
show-failed-attempts
ignore-empty-password
daemonize
