# Everforest Dark Medium desktop profile.
set $theme_env env XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway GTK_THEME=Everforest-Green-Dark-Medium GTK_USE_PORTAL=1 QT_STYLE_OVERRIDE=kvantum QT_QPA_PLATFORMTHEME=gtk3 QT_QPA_PLATFORM=wayland
output * bg #2d353b solid_color
exec_always --no-startup-id sh -c 'data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}; exec swaymsg output "*" bg "$data_home/backgrounds/dotfiles/3114699.jpg" fill'
#                    border   background text     indicator child_border
client.focused          #a7c080 #a7c080 #2d353b #a7c080    #a7c080
client.focused_inactive #475258 #2d353b #d3c6aa #475258    #475258
client.unfocused        #343f44 #2d353b #7a8478 #343f44    #343f44
client.urgent           #e67e80 #e67e80 #2d353b #dbbc7f    #e67e80
client.placeholder      #3d484d #2d353b #d3c6aa #3d484d    #3d484d
client.background       #2d353b
