# Everforest Dark desktop profile.
set $theme_env env XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway GTK_THEME=Everforest-Green-Dark GTK_USE_PORTAL=1 QT_STYLE_OVERRIDE=kvantum QT_QPA_PLATFORMTHEME=gtk3 QT_QPA_PLATFORM=wayland
output * bg #272e33 solid_color
exec_always --no-startup-id sh -c 'data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}; exec swaymsg output "*" bg "$data_home/backgrounds/dotfiles/3114699.jpg" fill'
#                    border   background text     indicator child_border
client.focused          #a7c080 #a7c080 #272e33 #a7c080    #a7c080
client.focused_inactive #414b50 #272e33 #d3c6aa #414b50    #414b50
client.unfocused        #2e383c #272e33 #7a8478 #2e383c    #2e383c
client.urgent           #e67e80 #e67e80 #272e33 #dbbc7f    #e67e80
client.placeholder      #374145 #272e33 #d3c6aa #374145    #374145
client.background       #272e33
