DISPLAY_NAME='Everforest Dark'
GTK_THEME='Everforest-Green-Dark'
GSETTINGS_ACCENT='green'
ICON_THEME='Papirus-Dark-Everforest'
KVANTUM_THEME='everforest-dark'
KDE_COLOR_SCHEME='EverforestDark'
KDE_ACCENT='167,192,128'
QT_STYLE_OVERRIDE='kvantum'
PREVIEW_COLORS='#272e33 #2e383c #a7c080 #83c092 #dbbc7f #e67e80'
WALLPAPER='3114699.jpg'
