# Everforest Dark
set -g status-style "bg=#1e2326,fg=#d3c6aa"
set -g status-left "#[fg=#272e33,bg=#a7c080,bold] 󰆍 #S #[fg=#d3c6aa,bg=#1e2326,nobold]"
set -g window-status-format "#[fg=#9da9a0,bg=#2e383c] #I:#W #[fg=#d3c6aa,bg=#1e2326]"
set -g window-status-current-format "#[fg=#272e33,bg=#d699b6,bold] #I:#W #[fg=#d3c6aa,bg=#1e2326,nobold]"
set -g window-status-activity-style "fg=#e69875,bold"
set -g window-status-bell-style "fg=#e67e80,bold"
set -g pane-border-style "fg=#2e383c"
set -g pane-active-border-style "fg=#d699b6"
set -g message-style "bg=#2e383c,fg=#d3c6aa"
set -g message-command-style "bg=#2e383c,fg=#a7c080"
set -g mode-style "bg=#d699b6,fg=#272e33,bold"
