# Catppuccin Macchiato desktop profile.
set $theme_env env XDG_CURRENT_DESKTOP=sway XDG_SESSION_DESKTOP=sway GTK_THEME=catppuccin-macchiato-blue-standard+default QT_STYLE_OVERRIDE=kvantum QT_QPA_PLATFORMTHEME=gtk3 QT_QPA_PLATFORM=wayland
output * bg #24273a solid_color
exec_always --no-startup-id sh -c 'data_home=${XDG_DATA_HOME:-"$HOME/.local/share"}; exec swaymsg output "*" bg "$data_home/backgrounds/dotfiles/leaves_line_neon_139772_2560x1600.jpg" fill'
#                    border   background text     indicator child_border
client.focused          #8aadf4 #8aadf4 #24273a #8aadf4    #8aadf4
client.focused_inactive #494d64 #24273a #cad3f5 #494d64    #494d64
client.unfocused        #363a4f #24273a #a5adcb #363a4f    #363a4f
client.urgent           #ed8796 #ed8796 #24273a #eed49f    #ed8796
client.placeholder      #5b6078 #24273a #cad3f5 #5b6078    #5b6078
client.background       #24273a
