DISPLAY_NAME='Catppuccin Macchiato'
GTK_THEME='catppuccin-macchiato-blue-standard+default'
GSETTINGS_ACCENT='blue'
ICON_THEME='Papirus-Dark'
KVANTUM_THEME='catppuccin-macchiato-blue'
KDE_COLOR_SCHEME='CatppuccinMacchiato'
KDE_ACCENT='138,173,244'
QT_STYLE_OVERRIDE='kvantum'
PREVIEW_COLORS='#24273a #363a4f #8aadf4 #a6da95 #eed49f #ed8796'
VSCODE_EXTENSION='catppuccin.catppuccin-vsc'
VSCODE_THEME='Catppuccin Macchiato'
WALLPAPER='leaves_line_neon_139772_2560x1600.jpg'
