Net/ThemeName "catppuccin-macchiato-blue-standard+default"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "Adwaita"
Gtk/CursorThemeSize 24
Gtk/FontName "JetBrainsMono Nerd Font 10"
Gtk/ApplicationPreferDarkTheme 1
Gtk/EnableAnimations 1
Gtk/DecorationLayout "icon:minimize,maximize,close"
Gtk/PrimaryButtonWarpsSlider 1
Net/EnableEventSounds 0
Xft/Antialias 1
Xft/DPI 122880
Xft/HintStyle "hintslight"
Xft/Hinting 1
Xft/RGBA "rgb"
Xft/lcdfilter "lcddefault"
Gdk/UnscaledDPI 122880
Gdk/WindowScalingFactor 1
